- 장소(카테고리): [예: 경주 황리단길]
- 미션 이름: [예: 대릉원 십원빵 먹기]
- 미션 종류: [수수께끼 / 인증샷 / 단순발견 중 선택]
- 미션 설명: [예: 십원빵의 앞면에 새겨진 신라의 대표 탑 이름은 무엇일까요?]
- 정답: [예: 다보탑] (수수께끼일 경우만 필수)
- 점수: [예: 100 GP] (생략 시 기본 100점)
- 이미지 이름: [예: bread.jpg] (생략 가능)

#.추가해야 할 문화재
1. 금관
[이 "금제대관"은 최초로 발견된 것으로, 이 때문에 무덤이름도 "금관총"이라 붙여졌다.

가지런한 긴 관테에 맞가지 세 개와 엇가지 두 개의 세움장식들이 조합된 전형적인 신라의 "금제대관"이다.

직각으로 꺾인 맞가지는 마디가 세 단이고, 줄기와 가지 사이가 넓다. 관테와 세움장식은 리벳으로 결합하였고, 관테의 양끝은 다른 재질을 덧붙여 묶었던 듯하다. 관테 아래에는 한 쌍의 긴 드리개가 달려 있다.]
{금관}

2. 금관(천마총)
[신라 금관(金冠)의 화려함을 잘 표현한 걸작 중의 하나이다. 신라 금관은 보통 둥근 테[臺輪]에 3개의 나뭇가지모양 장식[出字形立飾]과 2개의 사슴뿔모양 장식[鹿角形立飾]을 세운 뒤, 곱은옥[曲玉]과 달개[瓔珞]로 가득 장식한다.

둥근 테와 세움 장식판에는 가장자리를 따라 점열무늬[點列文]와 파상무늬[波狀文]를 장식하여 화려함을 더한다.

관을 착용했을 때 양쪽 볼에 해당하는 부위의 둥근 테 지점에는 가는고리[細環]로 코일처럼 길게 꼰 사슬로 만든 드리개[垂下飾]를 매단다. 신라는 지배자의 상징으로 금(동)관을 활용한 결과, 경주의 왕족이 착용한 것은 물론이고 재질과 모양은 달랐지만 지방의 수장도 소유할 수 있었다.

이는 금동관의 하사를 통해 지방의 수장을 회유하고 견제하려는 중앙정부의 의도가 담긴 것이었다. 그래서 고총과 화려한 위세품으로 통치기반을 확립해나가던 "마립간" 시기 즉 5세기대에 가장 화려하고, 불교가 국가의 이념으로 정착하기 시작하는 6세기 이후부터는 점차 퇴화한다. 천마총 금관의 나뭇가지 모양의 장식이 이전의 3단에서 4단으로 변한 점이 참조가 된다.  ]
{금관(천마총)}

3. 금제 관모
[금관과 함께 지배자를 상징하는 위세품의 하나이다. 금제관모는 모자의 모양이기는 하나 머리에 직접 착용하기에는 작기 때문에 가죽 혹은 자작나무 껍질로 만든 모자의 윗부분을 장식한 용도였던 것으로 보인다. 여러 매의 금판을 연결하여 만들며, 연결부위는 두툼한 금테를 두르고 금실로 마감하여 완성도를 높였다. 금판은 보통 앞면에 2개, 뒷면에 1개, 상부에 1개 등 모두 4개의 뚫음무늬[透彫文]가 장식된다. 뚫음무늬 형태는 T자, 마름모꼴, 반고리(半環), 변형된 용 모양 등이 많다. 뚫음무늬가 없는 부분은 점[點]을 직선 또는 곡선 모양으로 찍어 장식한다. 금제 관모는 "마립간"기로 불린 5세기대에 화려함이 절정에 달했다.]
{금제 관모}

4. 금제 새날개모양금관장식
[관모의 앞쪽에 꽂기 위해 만든 장식구이며, 중앙부의 꼬다리와 양쪽의 날개 모양 금판 등 모두 3장을 연결하여 만든다. 신라 왕족의 무덤에서 주인공이 착용한 상태로 발굴되는 금관이나 금제관모와 달리 부장궤에서 껴묻거리로 발견되는 경우가 많은 점이 특징의 하나로 꼽을 수 있다. 전체적인 모양은 크게 새의 날개[鳥翼形]와 나비[蝶形]로 나뉘어지는데, 이 중 새 날개 모양이 크기나 화려한 면에서 단연 앞선다. 꼬다리는 새의 머리와 같이 아래가 좁고 위가 넓으며, 단면은 "∧" 모양으로 접혀있다. 꼬다리의 양쪽에 붙는 날개모양 금판은 간략화된 용무늬 혹은 풀넝쿨무늬가 촘촘하게 뚫리고, 약 400개 이상의 달개[瓔珞]를 매다는 등 매우 화려하다. 또 관식과 뚫음무늬 가장자리를 따라서도 두드려셔 돌출시킨 점[點]을 연속적으로 배치하여 보는 이로 하여금 감탄을 자아내게 한다. 새날개모양 관 장식은 신라의 지배자를 상징하는 위세품이며, 신라의 중앙뿐만 아니라 지방의 수장묘에서도 출토된다.]
{금제 관모} 

5. 드리개 
[달개로 꾸민 금구슬을 엮어 만든 드리개인데, 무덤에 묻힌 이후 구슬의 특성상 흐트러져 원래 모양을 완전히 복원하기 어렵다. 귀금속제 구슬은 주로 목걸이에 많이 쓰이는데, 특이하게 드리개에 쓰였다. 드리개의 맨 아래에는 곱은옥을 달았다. 지금까지는 일반적인 드리개와 다르게 고리가 없는 것으로 알려져 왔다. 그러나 발굴 정황으로 보아, 함께 출토된 굵은고리 귀걸이와 합쳐져 하나의 드리개를 이루었을 가능성이 높다고 판단된다.]
{드리개}

6. 목걸이
[무덤 주인의 가슴 부위에서 출토되었다. 비록 하나의 줄에 묶여 있지만 재질, 형태, 크기, 색상에서 상당한 차이를 보인다. 마노제의 곱은옥, 다면옥, 둥근옥, 벽옥제의 대롱옥, 수정제의 대추옥, 유리제의 둥근옥이 하나로 결합되어 있다. 색상도 붉은빛과 푸른빛, 초록빛 등으로 다양하다. 특히 유리제 둥근옥 중에는 지름이 1.8㎝에 이르는 대형구슬도 포함되어 있는데, 그 표면에 파랑·노랑·빨강·흰색의 색유리로 사람얼굴과 오리, 꽃나무 무늬 등을 정교하게 만들어 붙였다.]
{목걸이}

7. 허리띠
[신라의 허리띠꾸미개는 허리띠 표면을 장식한 띠꾸미개와 허리띠 아래로 드리운 띠드리개로 구성되어 있다. 띠꾸미개는 네모꼴에 하트모양 드림이 달렸으며, 덩굴무늬에서 유래된 세잎무늬를 투조하고 달개로 화려함을 더했다. 띠드리개에는 질병을 다스리는 약병 또는 향수병, 풍요와 불사不死를 상징하는 물고기, 용무늬를 새긴 장식, 곱은옥, 숫돌을 끼웠던 두겁 등이 달려있다.]
{허리띠}

8. 장식보검
[경주 계림로 14호 돌무지덧널무덤에서 출토되었다. 원래는 꼭지가 달린 자루나 칼집에 나무가 부착되어 있었지만 썩어서 없어졌다. 칼집과 자루에는 얇은 금판을 전면에 입히고, 다시 작은 금판을 세워 붙여 물결·나뭇잎·원·타원·태극무늬 등을 만들어 조합시켰다. 이러한 무늬에는 붉은 마노와 재질을 알 수 없는 보석이 박혀있다. 전체적으로 기하학적인 무늬의 아름다움과 함께 보석의 붉은빛과 잿빛 및 금판의 금빛이 어우러져 화려하면서도 고급스러운 느낌을 준다.]
{장식보검}

9. 봉황무늬 고리자루큰칼
[신라의 고리자루큰칼은 고리의 형상에 따라 민무늬․세잎무늬[三葉]․세고리[三累]․용무늬․봉황무늬․용봉무늬로 나뉜다. 용과 봉황으로 장식된 큰칼은 이 가운데 가장 늦게 유행하였다. 이 봉황무늬 고리자루큰칼은 무덤 주인의 왼쪽 허리춤에서 출토되었다. 고리와 봉황은 한꺼번에 청동으로 만들어 도금하였다. 칼집과 칼자루는 나무에 금동판을 씌웠다. 칼집에는 작은 칼과 꼬챙이를 끼우는 부위가 있으며, 칼을 찰 때 끈을 끼웠던 마름모꼴의 고리도 있다.]
{봉황무늬 고리자루큰칼}

10. 팔뚝가리개 
[가운데 부속은 팔뚝을 보호하며, 팔꿈치 쪽이 넓고 팔목 쪽이 좁다. 이 부속에는 중심선을 따라 꽃봉오리 무늬를 도드라지게 새겼다. 팔목을 감싸는 부속은 가운데 부속의 양쪽에 경첩으로 달았으며, 팔목 안쪽에서 끈을 걸어 채울 수 있도록 나란하게 세 개씩 걸이를 달았다. 갑옷의 부속인 팔뚝가리개는 신라의 무덤에서 금동제, 은제, 철제가 출토되었으며, 그 모양이 대체로 비슷하다.]
{팔뚝가리개}

11. 유리제 잔
[우리나라에서 유리 제작 기술은 대략 기원 전후한 시점에 도입되어 천하석제 옥과 함게 장신구에 많이 활용되었다. 유리로 만든 그릇은 삼국 중 신라의 왕족 무덤에서만 출토되는 경향이며, 이 또한 신라 지배층의 독특한 장례문화와 연관된다. 유리 제품은 신라에서 자체적으로 제작하기도 하였지만, 황남대총에서 출토된 봉수병과 유리잔의 사례와 같이 유라시아 대륙과 중국 등을 거쳐 수입된 것도 상당수 있었음을 알 수 있다. 수입 제품은 봉수병에서 부러진 손잡이를 금실로 감아 보수한 흔적이 있는 점에서 미루어 볼 때 귀중하게 다루었을 가능성이 있다.]
{유리제 잔}

12. 금제 달개달린굽다리접시
[신라 왕족의 화려한 장례문화를 잘 보여주는 대표적 유물 중의 하나이다. 고구려와 백제는 신라에 비해 소박한 장례문화를 가지고 있어 부장품이 이처럼 화려하지는 않은 듯 하다. 신라 왕족이 돌무지덧널무덤 속에 묻힌 이유도 화려한 껴묻거리가 도난당하는 일이 없도록 하기 위함이라는 설도 있다. 금으로 만든 이 굽다리접시(金製瓔珞附高杯)는 무덤 속에 일반적으로 껴묻는 흙으로 만든 굽다리접시와 모양이 같다. 특히 굽다리의 중간 부분을 돌출시켜 2줄의 돌대를 만들고, 끝 부분에 금판을 덧대어 두툼하게 처리하여 최대한 토제 고배와 유사하게 만들었음을 알 수 있다. 다만 소재가 금속이라는 속상 상 접시 바닥 안쪽에 굽다리와 연결하기 위한 못이 있는 점은 다르다.]
{금제 달개달린굽다리접시}

13. 서수모양 주전자
[몸통은 거북, 머리와 꼬리는 용의 형상을 한 상상의 동물이 굽다리 위에 올려져 있는 이형토기異形土器이다. 흡사 고구려 고분벽화의 사신도四神圖에 나오는 현무玄武를 연상시키고 있어 무덤을 지키기 위한 특별한 의미를 담아 제작되었을 것으로 생각된다. 몸통 속은 비어있는데 등에는 깔때기 모양의 주입구注入口가 있고 가슴부분에는 대롱형의 귀때가 달려 있어 주전자와 같은 그릇으로 사용되었을 것으로 여겨진다.  ]
{서수모양 주전자}

14. 기마인물형토기
[국은 이양선 선생의 기증품으로 말탄 무사 모양의 토기이다. 말의 등에는 두 개의 뿔모양 잔이 좌우대칭으로 놓여져 있다. 말의 몸체에는 직사각형 모양의 판으로 엮어진 갑옷이 입혀져 있다. 말 등에는 무사가 앉아 있는데 역시 투구와 갑옷으로 단단히 무장한 상태이다. 오른 손에는 창을, 왼 손에는 방패를 들고 있는데, 세부적인 부분까지 표현되어 있어 당시 무사의 모습을 잘 보여준다.]
{기마인물형토기}

15. 토우장식 항아리
[목긴항아리[長頸壺]에 다양한 형상의 토우를 부착하여 최대의 장식효과를 낸 신라의 가장 대표적인 토우장식 토기이다. 항아리의 목과 어깨부분에는 개구리의 뒷다리를 물고 있는 뱀과 오리모양 토우를 세 곳에 일정한 간격으로 배치하고, 그 사이사이에 성기性器가 강조된 남자, 신라금新羅琴을 타고 있는 사람, 성행위 자세의 남녀상, 물고기․새․거북 등의 토우를 장식하였다. 이러한 장식토우들은 다산多産과 풍요豊饒를 기원하는 조형물로서 신라인의 생활상뿐만 아니라 자연과 조화된 당시 사람들의 정신세계를 보여주고 있다.]
{토우장식 항아리}

16. 약사여래
[약사여래는 모든 질병을 치료해 주고, 수명을 연장해 주며, 인간 생활의 전반에 이익을 주는 부처로 널리 신앙 되었다. 그의 정토는 동쪽에 있으며, 다채로운 보석으로 장식되어 화려한 모습이었다고 믿어진다. 백률사에 모셨던 이 약사여래는 높이가 180cm에 가까운 큰 체구에 조형적으로 완성미가 뛰어나 불국사의 아미타불, 비로자나불과 함께 통일신라 3대 금동불로 불린다. 현재 따로 만들어 끼운 두 손은 없어졌지만 팔을 든 자세와 『조선고적도보朝鮮古蹟圖譜』(1917년)에 실린 사진에 약단지로 보이는 물체를 왼손에 든 모습으로 보아 약사여래로 추정한다. 가슴에는 내의를 묶은 띠 매듭이 보이며, 몸 전체를 덮은 법의法衣는 자연스러운 옷 주름으로 신체의 입체감을 살렸다. 백률사에 봉안되어 있던 사진(1919년)에서는 온몸을 하얗게 칠한 모습이지만, 현재는 붉은색, 푸른색, 녹색, 검은색이 금동불 겉면에 남아 있다. 이러한 채색이 처음 불상을 만들 때부터 있었는지는 알 수 없지만, 겉에 금을 입힌 뒤 칠한 것으로 본다. 이 불상은 수준 높은 주조 기술로 대형 금동상을 제작했으며 뛰어난 조형성을 구현했다. 정수리와 머리, 등 뒤에 구멍이 있는데, 이는 불상을 만든 뒤 내형토內型土를 제거할 때 사용한 것이다. 구멍 테두리에 턱이 있는 것으로 보아 마감판을 끼운 것으로 보인다. 몸에는 일정한 간격으로 바깥틀과 안틀을 고정하는 틀잡이[형지型持]의 마감 흔적이 있다. 뒷면 위아래 두 곳에는 광배를 꽂았던 촉이 달려 있다.]
{약사여래}

17. 임신서기석
[비문(碑文)의 첫머리에 壬申年이라는 간지(干支)가 있고 내용 중에 충성을 서약하는 내용이 있어, 임신서기석(壬申誓記石)이라 한다. 비문은 구획선 없이 5행(行) 74자를 새겼다. 내용은 화랑도의 기본정신에 따른 충도(忠道)의 실천을 서약하는 것으로 되어 있다. 비석의 제작연대인 壬申年이 언제인지는 명확하지 않으나 화랑도가 번창하던 552년, 또는 612년으로 추정된다.]
{임신서기석}   

18. 성덕대왕신종
[이 종은 신라 제35대 왕인 경덕왕이 돌아가신 아버지 성덕대왕을 위하여 만들기 시작하여 그 아들인 혜공왕에 의해 771년에 완성되었다. 종의 꼭대기에는 용뉴(龍뉴)와 음통(音筒)이, 몸에는 위로부터 보상당초무늬를 새긴 문양띠, 그 아래는 4개의 유곽(乳廓), 4구의 비천상, 2곳의 당좌(撞座), 맨 아래에는 보상당초와 연꽃 문양띠가 양각되어 있다. 전체적으로 우아한 형태와 화려한 장식,아름답고 여운이 긴 종소리 등 우리나라의 종 가운데에서 가장 뛰어난 걸작이다.]
{성덕대왕신종}

19.금관 (황남동 황남대총 북분)
[둥근 머리테(大輪)에 3개의 나무모양 장식(樹枝形 立飾)과 2개의 사슴뿔모양 장식(鹿角形 立飾)이 금못에 의해 고정되어져 있으며, 6개의 드림장식(垂下飾)이 달려있는 금관이다. 둥근 머리태에는 위와 아래에 점무늬띠(點列文帶)의 구획이 있고 각각의 구획 안에는 파도모양(波狀文)과 그 사이에(彎曲部)에 점문이 돋아져 있다. 구획의 중간에는 반구형의 둥근 장식(半球形座金具)과 2개씩의 작은 구멍이 일정 간격으로 배치되어 각각 비취색 곡옥과 영락이 달려 있다. 영락은 머리테의 위와 아래에도 조밀하게 매달려져 있다. 드리개 장식은 중간식과 끝장식에서 차이를 보이고 있는데, 그 모습에 따라 세잎모양의 끝장식이 달린 2쌍과 곡옥이 달린 장식 1쌍으로 구분된다. 3개의 나무가지 장식(樹枝形 立飾)에는 19개씩의 반구형 장식(半球形座金具)이 각 가지의 중간과 끝에 균일하게 배치되어 있어 곱은옥(曲玉)과 영락이 매달려 있으며 그 중간중간에도 영락이 관찰됨. 사슴뿔모양 장식(鹿角形 立飾)은 4개의 중간 가지를 지니고 있으며, 반구형 장식(半球形座金具)에 곱은옥(曲玉)과 영락을 배치하는 방식은 나무가지장식(樹枝形 立飾)과 동일함. 이들 세움장식(立飾)들은 모두 가장자리에 점무늬(點列文)가 돋아져(打出) 있고 3개씩의 금못으로 머리테(帶輪)에 고정되어져 있는 상태이다.]
{금관 (황남동 황남대총 북분)}

20.금제 허리띠
[신라 사회에서 무덤에 묻힌 주인공이 착용한 허리띠의 모양과 재질은 사회적 신분을 반영한다. 왕족의 무덤에서는 금으로 화려하기 만든 허리띠가 거의 예외없이 출토된다. 허리띠는 넝쿨무늬를 투조하여 만든 방형판에 심엽형 수하식이 매달려 있다. 심엽형 수하식에는 둥근 달개가 매달려있다. 드리개는 방형과 타원형 금판을 연결하고 끝에는 약통, 물고기, 숫돌, 곱은옥 등 다양한 상징물을 매달았다. 이처럼 신라의 화려한 장례문화는 6세기 이후의 사회변화와 함께 점차 사라진다.]
{금제 허리띠}

21. 청동칼
[국은 이양선 선생의 기증품으로 청동검이다. 청동기시대에 사용되던 무기류이다. 대부분의 청동검에 비하여 길이가 매우 긴 편이고, 피홈 역시 약간 오목하게 들어간 점에서 차이가 있다. 한국식동검 중에서는 늦은 시기에 속하며, 비슷한 형태의 동검으로 대구 비산동 출토품이 있다.]
{청동칼}

22. 동제투겁창
[국은 이양선 선생의 기증품으로 청동투겁창이다. 청동기시대에 사용되던 무기류이다. 자루와 장착되는 부분이 약간 파손된 것 외에는 형태가 잘 남아 있다. 매우 특이한 형태의 투겁창인데, 비슷한 형태의 투겁창이 경주 입실리에서도 1점 출토된 적이 있다.]
{동제투겁창}

23. 은제타출무늬작은바리
[겉면은 연꽃무늬(蓮花文)로 위아래 단을 나누고 3각, 5각, 6각형의 무늬를 새겨놓았다. 가운데에는 거북이 등껍질 모양 안에 노루, 새, 호랑이, 말, 뱀, 가릉빈가, 사슴, 사람 등의 무늬가 두드려져 있다. 바닥은 보상화잎으로 가장자리를 두르고 그 씨방 안에는 고구려벽화에서 보이는 삼족오(三足烏) 모양의 새무늬를 바닥 안쪽에서 바깥으로 두드려 돌출시켜 놓았다. 겉면의 무늬들은 모두 두드린 후 날카로운 칼 등으로 세부 무늬를 정교하게 다듬어 놓은 것이다. 바닥과 몸통의 극히 일부가 복원된 상태이다.]
{은제타출무늬작은바리}

24. 고선사 삼층석탑
[고선사 삼층석탑은 감은사 동서 삼층석탑과 함께 통일신라시대 일반형석탑의 시원양식으로 평가되고 있다. 여러 개의 석재를 짜 맞추어 쌓는 방식을 적용하여 이중의 기단부基壇部와 삼층의 탑신부塔身部를 표현하였다. 1층 탑신석塔身石의 네 면에는 문비門扉가 새겨져 있으며 표면에는 금동판 등을 부착하기 위한 작은 구멍들이 확인된다. 석탑 이전 당시에 3층 탑신석에서 사리공이 확인되었으나 사리갖춤은 발견되지 않았다.]
{고선사 삼층석탑}

25. 금동초심지가위
[초의 심지를 자르는데 사용했던 가위다. 잘린 초와 심지가 떨어지는 것을 막기 위해 날 바깥에 각각 반원형의 테두리를 세워으며 손잡이쪽에 방울무늬[魚子文]와 당초무늬[唐草文]가 화려하게 장식되어 있다. 이와 같은 형태의 가위는 일본 정창원(正倉院)에도 소장되어 있는데 세부 장식 등에 약간의 차이가 있으나 매우 유사하다.]
{금동초심지가위}

26. 유리제 굽받침잔
[황갈색의 투명한 유리잔이다. 잔은 반원형(半球形)으로 아가리가 수직에 가깝게 바깥으로 벌어져 있으며, 아가리 끝부분은 둥글게 만들어졌다. 잔 전체에 물결무늬가 들어가 있으며 아래부분에 나팔모양으로 벌어지는 받침을 붙였다. 굽받침 역시 끝부분은 둥글게 만들어졌다. 안쪽 면에 구울때 생긴 기포(氣泡)와 이물질(異物質)이 많이 남아있다.]
{유리제 굽받침잔}


#.미션 종류는 수수께끼로 진행한다. 수수께끼는 초등학교 2학년 수준에 맞도록 진행하며, 내가 제시한 설명[ ]을 기초로 만든다. 위 형식에 맞게, 정답을 채워넣는다. 
#. 이미지 이름{ }만 제공할게 (확장자는 jpg, jpeg, png 모두 가능)
